#spring.application.name=emergencias
# Configuración del servidor de Spring Boot
server.port=8081

# Conexión a PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/bomberos_db
spring.datasource.username=postgres
spring.datasource.password=admin

# Configuración de JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# 'update' creará automáticamente las tablas faltantes si modificamos las entidades de Java
spring.jpa.hibernate.ddl-auto=update
# Muestra los comandos SQL en la consola de IntelliJ (útil para debuggear)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Permitir subida de archivos multimedia (Fotos/Videos) de hasta 15MB
spring.servlet.multipart.max-file-size=15MB
spring.servlet.multipart.max-request-size=15MB